### ISSUE TITLE
Missing cls for eslevier

### ISSUE THREAD

**Issue by vpadois** [iron76/ias-padois-et-al#1]
@iron76 : Can you push this file : elsarticle.cls ? It is missing and strangely I don't  find it.

**Comment by iron76** [comment]
Please try compiling the elsevier test in the ./template folder (added with sha af409e71fe2c6b9ae10a2698abc9003c7dbe95cc)

**Comment by vpadois** [comment]
There is no cls file in the template folder (I had tried that locally before).

**Comment by iron76** [comment]
It is what Elsevier provides. The .cls should be included in you latex distribution: http://www.elsevier.com/author-schemas/latex-instructions#elsarticle

**Comment by vpadois** [comment]
Indeed. I solved it by installing the proper ubuntu package. I will work on it this afternoon.
